# Generated by Django 5.2.8 on 2025-12-07 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='cover',
            new_name='cover_image',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='like_num',
            new_name='like_count',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='content',
            new_name='name',
        ),
    ]
