# Generated by Django 5.2.8 on 2025-12-18 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tag",
            old_name="count",
            new_name="global_count",
        ),
        migrations.AddField(
            model_name="book",
            name="top_tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="book",
            name="top_tags_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="booktag",
            name="base_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="booktag",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="booktag",
            name="user_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="tag",
            name="canonical",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="aliases",
                to="api.tag",
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="normalized",
            field=models.CharField(db_index=True, default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tag",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "ACTIVE"),
                    ("BLOCKED", "BLOCKED"),
                    ("MERGED", "MERGED"),
                ],
                default="ACTIVE",
                max_length=20,
            ),
        ),
    ]
