# Generated by Django 5.2.8 on 2025-12-18 15:11

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_count_tag_global_count_book_top_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookhistory",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userbookhistory",
            name="status",
            field=models.CharField(
                choices=[
                    ("READING", "읽는 중"),
                    ("FINISHED", "완독"),
                    ("STOPPED", "중단"),
                ],
                default="READING",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userbookhistory",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name="userbookhistory",
            index=models.Index(
                fields=["user", "status", "-last_read_at"],
                name="api_userboo_user_id_1c4511_idx",
            ),
        ),
    ]
