# Generated by Django 5.2.8 on 2025-12-19 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_userbookhistory_created_at_userbookhistory_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="recommendation_refer",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
