# Generated by Django 5.2.8 on 2025-12-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_review_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', through='api.ReviewTag', to='api.tag'),
        ),
    ]
