# Generated by Django 5.2.8 on 2025-12-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_book_recommendation_refer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="full_descript",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="one_line_descript",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="two_line_descript",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
