# Generated by Django 5.2.8 on 2025-12-19 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_book_full_descript_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookAIGenerationTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "실행중"),
                            ("DONE", "완료"),
                            ("FAILED", "실패"),
                        ],
                        default="RUNNING",
                        max_length=10,
                    ),
                ),
                ("requested", models.JSONField(blank=True, default=list)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_task_list",
                        to="api.book",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["book", "status", "-created_at"],
                        name="api_bookaig_book_id_130e08_idx",
                    )
                ],
            },
        ),
    ]
