# Generated by Django 5.2.8 on 2025-12-21 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_bookaigenerationtask"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="two_line_descript",
            new_name="abstract_descript",
        ),
        migrations.RemoveField(
            model_name="book",
            name="one_line_descript",
        ),
    ]
