# Generated by Django 5.2.8 on 2025-12-21 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_rename_two_line_descript_book_abstract_descript_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userbookhistory",
            name="location_unit",
            field=models.CharField(default="char", max_length=10),
        ),
    ]
