# Generated by Django 5.2.8 on 2025-12-17 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="coldstart_books",
            field=models.ManyToManyField(
                blank=True, related_name="interesting_traits", to="api.book"
            ),
        ),
        migrations.AddField(
            model_name="trait",
            name="coldstart_tags",
            field=models.ManyToManyField(
                blank=True, related_name="coldstart_traits", to="api.tag"
            ),
        ),
        migrations.AddField(
            model_name="trait",
            name="interesting_books",
            field=models.ManyToManyField(
                blank=True, related_name="interesting_books", to="api.book"
            ),
        ),
        migrations.AddField(
            model_name="trait",
            name="interesting_tags",
            field=models.ManyToManyField(
                blank=True, related_name="interesting_tags", to="api.tag"
            ),
        ),
        migrations.AddField(
            model_name="trait",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trait",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
